package br.com.furb.tagarela.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYMBOL_HISTORIC.
 */
public class SymbolHistoric {

    private java.util.Date date;
    private Long symbolID;
    private Long tutorID;
    private Long userID;
    private Long serverID;
    private Boolean isSynchronized;
    private long symbolLocalID;
    private Long id;

    public SymbolHistoric() {
    }

    public SymbolHistoric(Long id) {
        this.id = id;
    }

    public SymbolHistoric(java.util.Date date, Long symbolID, Long tutorID, Long userID, Long serverID, Boolean isSynchronized, long symbolLocalID, Long id) {
        this.date = date;
        this.symbolID = symbolID;
        this.tutorID = tutorID;
        this.userID = userID;
        this.serverID = serverID;
        this.isSynchronized = isSynchronized;
        this.symbolLocalID = symbolLocalID;
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Long getSymbolID() {
        return symbolID;
    }

    public void setSymbolID(Long symbolID) {
        this.symbolID = symbolID;
    }

    public Long getTutorID() {
        return tutorID;
    }

    public void setTutorID(Long tutorID) {
        this.tutorID = tutorID;
    }

    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public Long getServerID() {
        return serverID;
    }

    public void setServerID(Long serverID) {
        this.serverID = serverID;
    }

    public Boolean getIsSynchronized() {
        return isSynchronized;
    }

    public void setIsSynchronized(Boolean isSynchronized) {
        this.isSynchronized = isSynchronized;
    }

    public long getSymbolLocalID() {
        return symbolLocalID;
    }

    public void setSymbolLocalID(long symbolLocalID) {
        this.symbolLocalID = symbolLocalID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
